version: '3.8'

services:
  django:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: django-1
    command: ["python", "manage.py", "runserver", "0.0.0.0:8001"]
    ports:
      - "8001:8001"
    volumes:
      - .:/app
