# Generated by Django 5.1 on 2024-08-16 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yname', models.CharField(max_length=50)),
                ('yemail', models.CharField(max_length=50)),
                ('ynumber', models.CharField(max_length=50)),
                ('ymessage', models.TextField()),
            ],
        ),
    ]
