# Generated by Django 5.1 on 2024-08-16 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landingapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='yemail',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='ymessage',
            new_name='message',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='yname',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='ynumber',
            new_name='number',
        ),
    ]
